#spring  setup and common configuration
spring:
  profiles:
    active: local

---

spring:
  profiles: local
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  freemarker:
    charset: UTF-8
    check-template-location: true
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/templates

files:
  upload:
    dir: files/

# logging
# Lombok의 @Slf4j를 통해서 불필요하게 반복되는 코드수를 줄이기 위해서 가볍게 사용한다.
# 해당 설정은 logs폴더에 남겨질 것이다. 파일은 하루 단위로 나눠져서 gz파일로 이전 날짜로 파일이 남는다.
# 좀 더 세분화하면 쌓이는 로그의 파일 사이즈로 분리할 수 있지만 기본적인 옵션으로 남긴다.
logging:
  file: logs/local-log.log
  level:
    root: INFO
    org:
      springframework:
        web: INFO
  pattern:
    # console에 찍히는 로그 형식 정의
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    # console에서 로그는 위에 형식으로 찍히지만 파일로 씌여질 때 해당 패턴으로 찍는다. 
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"